### PR TITLE
The start of some API docs

### PR DESCRIPTION
**Pull request by hassox**

### CODE REVIEW

**Comment by nicholascloud** [comment]
I would like to contribute to docs as well. Would it be helpful to do this in the repo wiki?

**Comment by mjackson** [comment]
@nicholascloud Great idea. Let's get the wiki going again. I'm hesitant to put it up right now because there's a lot of misinformation currently in there (old stuff) but I can put it back up if you'd like to clone it.

**Comment by nicholascloud** [comment]
@mjackson That would be great! Maybe we could just put a big "under construction" gif at the top of the front page :)

under construction

**Comment by mzedeler** [comment]
What happened? Why not merge?

**Comment by mjackson** [comment]
This project is no longer maintained.

**Comment by mzedeler** [comment]
Maybe just press the green button here:

https://github.com/mjackson/mach/pull/76

**Pull request closed without merging**
